dist: xenial
sudo: true
language: python
python:
- '3.7'
git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
script:
  - bash data/setup.sh
  - python data/process.py
  - cd sql && sqlite3 nutra.db ".read init.sql"
